### ISSUE TITLE
separate yaml file creation from the xml diff element

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/skilletlib#21]
Either have an option to generate the yaml piece or move to a different skillet.

When doing iterative design with skillets, the one-time yaml file creation is overhead and annoyance. Ideally the xml diff piece would stand alone for ongoing skillet test and updates.

**Comment by nembery** [comment]
This can currently be accomplished by the following steps:

Panhandler -> Collections -> All Skillets Collection -> search for 'Generate Skillet Snippets From Device ' and run from there. It currently captured the output into a variable, so 'clicking the 'show captured outputs' button will show the raw snippet output.

Note, I do not have this skillet in the 'Skillet Builders' collection to keep that collection 'tidy'. The normal use case is to use this tool from the 'Generate Skillet from Device Workflow' workflow. This can be changed though pretty easily. Would be good to go through all available tools and decide what should go where collection wise.
