### ISSUE TITLE
skillet gen feature for set commands

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/skilletlib#24]
Not sure best way to implement but can be helpful for quick creation of set commands even if out of order initially. The user can test/correct ordering.

(1) text file diff in the skillet gen workspace showing delta between 2 text files with set commands

(2) conversion of xml to set based on the xml diff. Not sure how this works for config elements vs a full config file

The first option would require console capture of set commands before and after as input to the set diff. There is no easy way to output unless the xml files are converted to set and then a diff performed. This model allows for online options to extract named xml files using the api, convert to set, then diff.

**Comment by nembery** [comment]
This has been implemented using the ' Generate set commands from configs' Skillet tool. This currently works by comparing two XML files, but an online mode should be possible as well. Also with the extra workflow work to select different variants of online / offline can make this even easier.
