### ISSUE TITLE
embedded element skillet not working - ready in panHandler?

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/skilletlib#29]
Receiving error: Could not push Configuration: Malformed snippet section in meta-cnc file for mySkillet. no contextual error message and yamllint is good to go.

Using the skilletBuilder tutorial config diff and then adding variables + text alignment for element readability.

The yaml file at: https://github.com/scotchoaf/panos_tools/blob/develop/genTest/.meta-cnc.yaml

Also noticed the debug option doesn't work for the element mode yet to validate elements and variable values.

**Comment by nembery** [comment]
it is not in panhandler yet, will be before summit though.

**Comment by nembery** [comment]
this has been added to panhandler and is ready for test
