### ISSUE TITLE
create a pass_message option in tandem with the fail_message

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/skilletlib#33]
Even when a test passes provided contextual data to the user, especially when data is exported or reviewed across multiple firewalls. 

Expected messages would include named objects (tags, profiles, groups) and any compliance/audit reference material based on the type of skillet test.

**Comment by nembery** [comment]
This has been implemented and an example can be found here: https://github.com/PaloAltoNetworks/skilletlib/blob/develop/example_skillets/fail_message/.meta-cnc.yaml#L42
