### ISSUE TITLE
create a local collection based on user selected skillets

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/skilletlib#36]
currently collection names are hardcoded by the skillet builder.

This feature would allow a panHandler user to self-select skillets and assign them to locally named collections outside the original collections. User can then group skillets and make them easy to find for demos and customer engagements using their own naming convention.

A key example is the K12 skillet that has locally copied IronSkillet and the content update skillets into their repo just to add their Education collection name. Instead of skillet copies they could create a local collection called Education. Once grouped they could shared the set of skillet names so other customers could create similar groupings.

**Comment by nembery** [comment]
note, this should be opened on panhandler or cnc repo. 

This requires panhandler to have multiple databases, as cnc apps are loaded dynamically at run time. Will investigate if this is possible, desirable given amount of time it might take to implement

**Comment by scotchoaf** [comment]
Trying out Favorites in Dev. First notes based on using the Favorites features. Not sure if these need various cards/issues for tracking. Suggestions at this point and not hard requirements.

1- when adding a skillet to a collection, prefer to stay on the current page vs going to the favorites. Too many clicks to add to Favorites then go back to the repo detail or collection view to pick another. This assumes users are adding multiple skillets to build out a favorite collection, example with a new import.

2- Need a way to remove a skillet from Favorites

3- Possible to rename a favorite without a delete and build again

4- Related to appetizer, is this where we use a dropdown menu based on Favorites? Now instead of one repo I can import several and create a favorites collection quick select menu instead of just tiles. As example I have a Favorites call Mobile Workforce with GP and PA. I could also see SecOps, Cloud Deploy, etc. based on user grouping.

5- More long term, would be great to share Favorites where I can create a collection of Skillets and share using some type of export or link. I think this starts to look like micro skillets where I import Favorites and panHandler will import all the skillet pieces I need. Examples here are SE training or bootcamps to load key skillets. This might also replace the static list in panHandler with a hosted option based on recommended Favorites.

**Comment by scotchoaf** [comment]
Also - not sure how to change the source for an existing card. Does it require manually copying content over to a new card?
