### ISSUE TITLE
Include branch name as part of import skillet repo link

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/skilletlib#37]
When importing a skillet both the skillet repo url and branch are required yet only the branch url is provided as a clickable link at the top of the page.

This allows for easy jump to the exact repo/branch when using the link.

**Comment by nembery** [comment]
added github detection for repo links and will link directly to the proper URL when the repo is pointing to github

**Comment by nembery** [comment]
note, this is actually a panhandler feature and not specific to skilletlib
