### ISSUE TITLE
If local dir exists when using load_from_git() and repo is non-existent, it still works

### ISSUE THREAD

**Issue by punisherVX** [PaloAltoNetworks/skilletlib#56]
## Describe the bug
If the local copy of the repository exists in the directory specified and the wrong repo name (misspelled, typo, etc.) is sent to the method, it still works.  It looks like it is squashing the error returned from the Git.clone() method.

## Expected behavior
It should be expected that if the repository URL is incorrect, we should get back an exception stating that

## Current behavior
Currently still get back the local dir listing - which technically hasn't been updated because the repository name is wrong. 

## Possible solution
Catch the exception from the clone method and raise it rather than sending back the list of the local directory.

## Steps to reproduce
Here is a try/except block that I use to access this method.  Just call it twice with 2 different repository names, first one should be good, second one can have a typo in it.

```try:
        skillets = sl.load_from_git(jsonData['repo_url'], jsonData['repo_name'], jsonData['repo_branch'], local_dir=localDir)
        for s in skillets:
            pprint(vars(s))
    except GitCommandError as gce:
        abort(make_response(jsonify(message=gce.stderr),404))
    except Exception as err:
        abort(500,err)
```

Would expect that at least the abort would hit, though if you try a non-existent repo on the first run, you will get the GitCommandError exception.

## Context
Just found this while writing API wrapper for skilletlib

## Your Environment
Meh

**Comment by nembery** [comment]
fixed in commit: 760456f3b6a0fd7905b03acaffd8f39ce2abcc2c 
give it a try and let me know if I can close

Thanks!

**Comment by nembery** [comment]
release 0.1.3 has been pushed with this fix btw

**Comment by punisherVX** [comment]
Tested and works as needed.  Closing
